config/routes.rb
Rails.application.routes.draw do   

  resources :investments, only: [:new, :create]

  resources :dashboard, only: [:dashboard, :show]

  get 'investors/index'

devise_for :investors do delete '/investors/sign_out' => 'devise/sessions#destroy' end
  root 'investors#dashboard'
  resources :investors, only: [:edit, :update, :show]

get 'networks/show'

get 'charts/index' => 'charts#index'
get 'student_impacts/index' => 'student_impacts#index'

post 'student_impacts/index' => 'student_impacts#index'

post '/network_mailer' => 'networks#invite_investors'

  

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/investment.rb
class Investment < ActiveRecord::Base
	belongs_to :investor
	belongs_to :school
	belongs_to :series

	validates :amount, :school_id, :series_id, :investor_id, presence: true 

	def self.create(investment_params) 
		investment = Investment.new(investment_params)
		investment_amount = investment_params[:amount].to_f

		if investment_amount < 10000
			return [false, "The minimum investment is $10,000", investment]
		end

		if investment.save!
			return [true, "You have successfully invested.", investment]

		end

		
			
		
	end

end

app/models/investor.rb
class Investor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_one :school
	has_many :investments
	# has_many :series, through: :investments



	validates :first_name, :last_name, :origin_country, :resident_country, presence: true 
	validates :email, uniqueness: true 
	# validate :resident_country_school_country 

	# private 
	# def resident_country_school_country 
	# 	if School.find(school_id).location.to_s == self.resident_country.to_s 
	# 		errors.add(:resident_country, "is the same as the school location, which is prohibited")
	# 	end
	# end 
end

app/models/school.rb
class School < ActiveRecord::Base
	belongs_to :investor
	belongs_to :series
	geocoded_by :location
	before_save :geocode

end

app/models/series.rb
class Series < ActiveRecord::Base
	has_many :investments
	has_one :school


def show 
	@series = current 


end 

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :school
	belongs_to :series
	validates_presence_of :place_of_origin, :origin_country
	geocoded_by :hometown
	before_save :geocode, :if => :place_of_origin_changed? || :origin_country_changed?



	def hometown
		(self.place_of_origin + "," + self.origin_country)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller? 


  protect_from_forgery with: :exception

	def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :origin_country, :resident_country, :program, :grad_year, :school_id, :alumnus_status, :email]
  end

end	

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
    def index
      data_table = GoogleVisualr::DataTable.new
      data_table.new_column('string', 'Year' ) 
      data_table.new_column('number', 'Sales') 
      data_table.new_column('number', 'Expenses')

      # Add Rows and Values 
      data_table.add_rows([ 
        ['2004', 1000, 400], 
        ['2005', 1170, 460], 
        ['2006', 660, 1120], 
        ['2007', 1030, 540] 
      ])
      option = { width: 400, height: 240, title: 'Company Performance' }
      @chart = GoogleVisualr::Interactive::AreaChart.new(data_table, option)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
  end
  def show
  	render 'before_returns'
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

	def new 
		@investment = Investment.new
	end

	def create
		@investor = current_investor
		@success, @message, @investment = Investment.create(investment_params)

		if @success
			current_investor.investments << @investment
			flash[:success] = @message
			redirect_to investor_path(:id)
		else 
			flash[:error] = @message
			redirect_to new_investment_path
		end 
		
	end

	private 

	def investment_params
		params.require(:investment).permit(:series_id, :amount, :school_id, :investor_id) 
	end 
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
		before_action :authenticate_investor!

 def dashboard
  end

 def show
  	render 'before_returns'
  end

def network
	render 'network'
end

end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  def show
  end

 def invite_investors
    name = params[:name]
    email = params[:email]
    sender = Investor.find(params[:sender_id])
    body = params[:body]
    NetworkMailer.invite_investor(email, name, sender, body).deliver

    redirect_to root_path
  end
	
end

app/controllers/student_impacts_controller.rb
class StudentImpactsController < ApplicationController
	before_action :authenticate_investor!

	def index
		# id = []
		# id << params[:school][:id]
		series_list = current_investor.investments.pluck(:series_id).uniq
		@investor_students = Student.where(:series_id => series_list).select(:series_id, :f_name,:l_name, :profile_pic, :longitude, :latitude, :school_id)
		# @investor_students = @investor_students.where.not(:school_id => id)
		
		school_list = current_investor.investments.pluck(:school_id).uniq
		# school_list -= id
		@investor_schools = School.where(:id => school_list)
		@geojson = Array.new

		@investor_students.each do |investor_student|
			school = School.find(investor_student.school_id)
  			@geojson << {
    		type: 'Feature',
    		geometry: {
      			type: 'Point',
      			coordinates: [investor_student.longitude, investor_student.latitude]
    		},
   			 properties: {
      		title: investor_student.f_name + " " + investor_student.l_name,	
      		icon: {
      			iconUrl: investor_student.profile_pic,
      			iconSize: [50, 50],
      			iconAnchor: [25, 25],
      			popupAnchor: [-3, -25],
      			className: "nav-thumbnail",
      		}
		      # :'marker-color' => '#00607d',
		      # :'marker-symbol' => 'circle',
		      # :'marker-size' => 'large'
			    }

			  }

			  # @geojson <<
			  # {
     #   type: "Feature",
     #   geometry: {
     #     type: "LineString",
     #     coordinates: [
     #        [investor_student.longitude, investor_student.latitude],
     #        [school.longitude, school.latitude]
     #      ]
     #    },
     #         }
			end

			@investor_schools.each do |investor_school|
				@geojson << {
    		type: 'Feature',
    		geometry: {
      			type: 'Point',
      			coordinates: [investor_school.longitude, investor_school.latitude]
    		},
   			 properties: {
      		title: investor_school.name,	
      		icon: {
      			iconUrl: '/assets/school_thumbnail.png',
      			iconSize: [50, 50],
      			iconAnchor: [25, 25],
      			popupAnchor: [-3, -25],
      			className: "nav-thumbnail",
      		}
		      # :'marker-color' => '#00607d',
		      # :'marker-symbol' => 'circle',
		      # :'marker-size' => 'large'
			    }

			  }
			end

		
			  respond_to do |format|
 				 format.html
 				 format.json { render json: @geojson }  # respond with the created JSON object
			end

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/student_impacts_helper.rb
module StudentImpactsHelper
end

app/views/dashboard/_header.html.erb
<div class="header1 container">
	<div class="row">
		<div class="col-sm-1" style = "padding-left:0px; padding-right:0px;" >
			<div id="st-trigger-effects" class=" container column">
				<button data-effect="st-effect-1" class = "Btn">
					<em></em>
				</button>
			</div>
		</div>
		<div class="col-sm-4" style = "padding-left:0px; padding-right:0px;">
			<div class = "prodigy_logo">
			<img id="Prodigy_Finance" src="../assets/logo-light.png" height="10%" width="10%">
			</div>
		</div>
		<div class = "col-sm-7">
			<div class = "log_out">
			<%= link_to("Log out", destroy_investor_session_path, :method => :delete) %>
			</div>
		</div>
	</div>
</div>

app/views/dashboard/_initial_dash.html.erb
<div class = "container full-page">
<br></br>
<div class = "col-md-1">
</div>
<div class = "col-md-5">
	<div class = "container welcome" style ="width: 100%">
		<h1> Welcome, John</h1>
	</div>
</div>
<div class = "col-md-6">
</div>
<!-- investment buttons -->
<div class = "row">
	<div class = "col-md-10">
		<div class = "row">
			<div class = "investment_buttons">
				<div class = "col-md-3">
				</div>
				<div class = "col-md-3">
					<%= button_to 'New Investment', new_investment_path, :class => 'new_investment'%>
				</div>
				<div class = "col-md-3">
					<button type="button" class="btn btn-default btn-lg new_investment">Continue Application</button>
				</div>
			</div>
			<div class = "col-md-3">
			</div>
		</div>
		<br></br>


		<div class = "overview container" style = "border: solid;">
			<div class = "row">
				<div class = "col-md-12">
					<h2 class = "container" style = "width:100%;">
						Overview:
					</h2>
				</div>
			</div>
			<div class = "row container" > 
				<div class = "col-md-12">
					<h5 style = "width:100%;">
						Still have questions about the investor process?
					</h5>
				</div>
			</div>
			<div class = "row container">
				<div class = "col-md-12">
					<h5 style = "width:100%;">
						Seach for answers in our knowledge base.
					</h5>
				</div>
			</div>
			<div class = "row">	
				<div class = "col-md-4" style = "padding:0;">
				</div>
				<div class = "col-md-4" style = "padding:0;">
					<button type="button" class="btn btn-default  btn-lg
					new_investment knowledge" href = "https://prodigyinvest.zendesk.com/hc/en-us">Knowledge Base</button>
				</div>
				<div class = "col-md-4" style = "padding:0;">
				</div>
			</div>
		</div>

	</div>
	<div class = "col-md-2">
		<!-- stats side marketing -->
			<!-- <div class = "row">
			<div class = "col-md-3" style = "border:solid"> -->
				<div class = "stats container"> 
					<ul style = "text-align:center;">
						<li>to date</li>
						<ul>
							<li>$50M</li>
						</ul>
						<li>DISBURSED</li>
						<li>to over</li>
						<ul>
							<li>1209</li>
						</ul>
						<li>STUDENTS</li>
						<li>from</li>
						<ul>
							<li>90</li>
						</ul>
						<li>COUNTRIES</li>
						<li>with a</li>
						<ul>
							<li>99%</li>
						</ul>
						<li>REPAYMENT RATE</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<!-- overview to get to general knowledge base -->


	<!-- seperate two divs -->

	<script type="text/javascript">
		$(function () { 
			$("#fact-card_modal").modal({show: false});
		});  
	</script>

	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		$('.dropdown-toggle').dropdown()
		$(function() {
			$("#select_school li:first").click(function(){
				$('ul:first',this).toggle();
			})
		});
	</script>



	<br></br>
	<!-- div to find out more about school terms and students to invest -->
	<div class = "row">
		<div class = "col-md-10">
			<div class = "investment container" style = "border:solid;">
				<div class = "row" >
					<h2 class = "container" style = "width:100%;">
						School Specific Terms:
					</h2>
				</div>
				<br></br>
				<div class = "row" >

					
					<div class = "col-md-3">
					</div>
					<div class = "col-md-6">
						<div class="dropdown container" id = "select_school" style = "width:100%; text-align:center" >
							<a href="#" class="btn-lg button--blue dropdown-toggle km-investor-home-banner-dropdown select_button col-md-6" data-toggle="dropdown" style = "width:100%; margin:0;">
								Select School 
								<span class="caret" ></span>
							</a>  
						</div>          
						<ul class="dropdown-menu"  role="menu" aria-labelledby="dLabel">
							<% School.all.each do |school| %>
							<li><%= link_to school.name, '#' %></li>
							<% end %>
						</ul>
					</div>
					<div class = "col-md-3">
					</div>
				</div>

				<br></br>	
			<!-- <div class = "col-md-3">
		</div> -->
		<div class = "col-md-6"  style = "text-align:center;">
			<div class="thumbnail-container">
				<img src="/assets/school_thumbnail.png" class="img-thumbnail">
				<div id =  "fact-card_modal" data-target=".bs-example-modal-lg">
					<a href="#" class="btn"  data-toggle="modal" data-target=".fact-card" id = "fact-card_modal">Fact Card</a>
				</div>

			</div>
		</div>

		<div class = "col-md-6" style = "text-align:center;">
			<div class="thumbnail-container">
				<img src="/assets/school_thumbnail.png" class="img-thumbnail">
				<a href="#" class="btn"  data-toggle="modal" data-target= ".student-modal" id = "fact-card_modal">Students</a>
			</div>
		</div>
	</div>
</div>

<!--   -->
<div class = "col-md-2">
	<div class = "relationship_manager" style = "text-align:center;"> 
		<div class = "txt" > <h5> Contact Jenn, <br> Your Investor Relations Manager</h5></div>
		<center>
			<img src="/assets/jenn-portrait.png" class="nav-thumbnail">
		</center>
		<div class = "contact-links">
			<button type="button" class="btn btn-group-justified glyphicon glyphicon-phone ">Schedule a Call</button>
			<button type="button" class="btn btn-group-justified glyphicon glyphicon-envelope " style = "border-top:0px">Send a Message</button>
		<!-- 
		<a class= "icon icon-lab" href="#">Schedule a Call</a> <br>
		<a class= "icon icon-mail" href="#">Send a Message</a> -->
	</div>
	
</div>
</div>



<%= content_for :script do %>
<div class="modal fade fact-card" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel">Fact-Card</h4>
			</div>
			<div class="modal-body">
				This is the facts about the school
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade student-modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="myModalLabel">Students</h4>
			</div>
			<div class="modal-body">
				This is the list of students
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/dashboard/_navbar.html.erb
<div id = "dashboard">
<div id="st-container" class="st-container">
		<!-- 	
			example menus 
			these menus will be on top of the push wrapper
		-->
		 

		<nav class="st-menu st-effect-1" id="menu-1">

			<h2 class="icon icon-stack"></h2>
			<ul> 
				
				<li><a class="icon icon-data" href="#">Current Investments</a></li>
				<li><a class="icon icon-data" href="#">Past Investments</a></li>
				<li><a class="icon icon-data" href="#">Social Impact</a></li>
				<li><a class="icon icon-data" href="#">Networking</a></li>
				<li><a class="icon icon-data" href="#">Documents</a></li>
				<li><a class="icon icon-data" href="#">Account</a></li>
				<li><a class="icon icon-data" href="#">FAQ</a></li>

			<h2> Help</h2>
					</nav>

		<!-- content push wrapper -->
		<div class="st-pusher">

			<!-- 	
				example menus 
				these menus will be under the push wrapper
			-->
			<div class="st-content"><!-- this is the wrapper for the content -->
				<div class="st-content-inner"><!-- extra div for emulating position:fixed of the menu -->
					<!-- Top Navigation -->
					<header>	
						<%= render "header" %>
					</header><!-- /main -->
				</div>
				<!-- /st-content-inner -->
				<%= render "initial_dash" %>

				<footer>
					<%= render "footer" %>
				</footer>
			</div><!-- /st-content -->
		</div><!-- /st-pusher -->
		<!-- /st-contain -->
		<script src="/assets/classie.js"></script>
		<script src="/assets/sidebarEffects.js"></script>
</div>
</div>

app/views/dashboard/dashboard.html.erb
<%= render "navbar" %>

app/views/investments/_footer.html.erb
<div class = "container footer">
	<div class = "row">
		<ul class="social-links" style = "font-size: 13px; line-height; 13px;">
			<div class = "col-md-5" style = "text-align:right">
				<li>
					<a href="http://twitter.com/prodigyfinance" target="_blank"><img src="/assets/icon-social-twitter.png">Twitter</a>
				</li>
			</div>
			<div class = "col-md-2">
				<li><a href="http://facebook.com/prodigyfinance" target="_blank"><img src="/assets/icon-social-facebook.png">Facebook</a>
				</li>
			</div>
			<div class = "col-md-5" style = "text-align:left">
				<li><a href="http://www.linkedin.com/company/prodigy-finance" target="_blank"><img src="/assets/icon-social-linkedin.png">Linkedin</a>
				</li>
			</div>
		</ul>
	</div>
	<div class = "row" style = "margin-top: 5px;">
		<ul class = "inquiries" style = "margin: 0 auto">
			<div class = "col-md-4" style = "margin-right: 45px;">
			</div>
			<div class = "col-md-1" style = "padding: 0px; text-align:center;" >
				<li>
					<a href="/help">Help</a>
				</li>
			</div>
			<div class = "col-md-1" style = "padding: 0px; text-align:center;">
				<li>
					<a href="/faq">FAQ</a>
				</li>
			</div>
			<div class = "col-md-1" style = "padding: 0px; text-align:left;">
				<li>
					<a href="/about_us">About us</a>
				</li>
			</div>
		</ul>
		<div class = "col-md-3">
		</div>
	</div>
	<div class = "col-md-2">
	</div>
	<div class = "row">
		<div class = "col-md-12">
			<div class="copy-right alpha omega" style = "text-align:center">
				<p style="font-size: 11px; line-height: 12px;">
					© Prodigy Finance Ltd 2007 -  2014. All Rights Reserved. Prodigy Finance Ltd is incorporated in the United Kingdom (Company Number 05912562) and registered with the Office of the Information Commissioner (Reg. No. Z9851854). Prodigy Finance Ltd is authorised and regulated by the Financial Conduct Authority, and entered on the Financial Services Register under firm registration number 612713.  Prodigy Finance Ltd is an appointed representative of BriceAmery Capital Ltd which is authorised and regulated by the Financial Conduct Authority. Prodigy Finance Ltd carries out both regulated and unregulated business. Prodigy's registered address is Palladium House 1-4 Argyll Street, London, W1F 7LD.
				</p>
			</div>
		</div>
	</div>

app/views/investments/new.html.erb
<div class="flash_messages">
	<% if flash[:success] %>
	<div class="success">
	<%= flash[:success] %>
	</div>
	<% end %>
	<% if flash[:error] %>
	<div class="error">
		<%= flash[:error] %>
	</div>
	<% end %>
</div>


<body class="investment_body">	
		<div class="signin_logo">
			 <a href="http://prodigyfinance.com"><img align= "center" id="PF_Logo" src="../assets/LILLY.png" height="16%" width="16%"> 
			 </a>
		</div>

	<div class="investment_form">
		<div class="signin_header">
			<h2>Create a New Investment</h2>
		</div>

<div class="formforinvestment">
		<%= form_for @investment, url: investments_path do |f| %>
		  <div class="invest_label"><%= f.label :school_id %><br /> </div>
		  <div class="invest_field"> <%= f.collection_select(:school_id, School.all, :id, :name) %></div>

		  <div class="invest_label"><%= f.label :series_id %><br /> </div>
		  <div class="invest_field"><%= f.collection_select(:series_id, Series.all, :id, :series_number) %> </div>

		  <div class="invest_label"><%= f.label :amount %><br /> </div>
		  <div class="invest_field"><%= f.number_field :amount, :class => 'form-control borrow' %></div>

		  <div class="invest_field"><%= f.hidden_field :investor_id, :value => current_investor.id %></div>
</br>
		  <div class= "signin_button_row"><%= f.submit "Submit", class:"signin_button" %></div>

		<% end %>

 		

		</div>
	</div>
</br> </br> </br>
<%= render 'footer' %>

<body>

app/views/investors/_investor_relations_manager.html.erb
<div class = "relationship_manager" style = "text-align:center;"> 
		<div class = "txt" > <h4 style="margin-bottom:0; padding-top:1em"> Meet Jenn,</h4><h5> Your Investor Relations Manager</h5></div>
		<center>
			<img src="/assets/jenn-portrait.png" class="nav-thumbnail">
		</center>
		<div class = "contact-links">
			<button type="button" class="btn btn-group-justified"><span class="glyphicon glyphicon-phone"></span> Schedule a Call</button>
			<button type="button" class="btn btn-group-justified" style = "border-top:0px"><span class=" glyphicon glyphicon-envelope"></span>  Send a Message</button>
		<!-- 
		<a class= "icon icon-lab" href="#">Schedule a Call</a> <br>
		<a class= "icon icon-mail" href="#">Send a Message</a> -->
	</div>

app/views/investors/_navbar.html.erb
<div id = "dashboard">
<div id="st-container" class="st-container">
		<!-- 	
			example menus 
			these menus will be on top of the push wrapper
		-->
		

		<nav class="st-menu st-effect-2" id="menu-2">
			<h2> Investor Avatar</h2>
			<ul>
				<li><a class="dashboard" href= "/" >Dashboard</a></li>
				<li> <%= link_to "New Investment", new_investment_path %></li>
				<li><a class="current_investment" href="#">Current Investments</a></li>
				<li><a class="pastinvestment" href="#">Past Investments</a></li>
				<li><a class="social_impact" href="#">Social Impact</a></li>
				<li><%= link_to "Network", networks_show_path %></li>
				<li><a class="document" href="#">Documents</a></li>
				<li><a class="account" href="#">Account</a></li>
				<li><a class="faq" href="#">FAQ</a></li>
				<li><%= link_to "Logout", destroy_investor_session_path, method: :delete%></li>
			</ul>
		</nav>

		<!-- content push wrapper -->
		<div class="st-pusher">

			<!-- 	
				example menus 
				these menus will be under the push wrapper
			-->
			<div class="st-content"><!-- this is the wrapper for the content -->
				<div class="st-content-inner"><!-- extra div for emulating position:fixed of the menu -->
					<!-- Top Navigation -->
					<header>	
						<%= render "header" %>
					</header><!-- /main -->
				</div>
				<!-- /st-content-inner -->
				<%= render "initial_dash" %>

				<footer>
					<%= render "footer" %>
				</footer>
			</div><!-- /st-content -->
		</div><!-- /st-pusher -->
		<!-- /st-contain -->
		<script src="/assets/classie.js"></script>
		<script src="/assets/sidebarEffects.js"></script>
</div>
</div>

app/views/investors/before_returns.html.erb
<div id = "dashboard">
<div id="st-container" class="st-container">
		<!-- 	
			example menus 
			these menus will be on top of the push wrapper
		-->
		

		<nav class="st-menu st-effect-2" id="menu-2">
			<h2> Investor Avatar</h2>
			<ul>
				<li><a class="dashboard" href= "/" >Dashboard</a></li>
				<li> <%= link_to "New Investment", new_investment_path %></li>
				<li><a class="current_investment" href="#">Current Investments</a></li>
				<li><a class="pastinvestment" href="#">Past Investments</a></li>
				<li><a class="social_impact" href="#">Social Impact</a></li>
				<li><%= link_to "Network", networks_show_path %></li>
				<li><a class="document" href="#">Documents</a></li>
				<li><a class="account" href="#">Account</a></li>
				<li><a class="faq" href="#">FAQ</a></li>
				<li><%= link_to "Logout", destroy_investor_session_path, method: :delete%></li>
			</ul>
		</nav>
		<!-- content push wrapper -->
		<div class="st-pusher">

			<!-- 	
				example menus 
				these menus will be under the push wrapper
			-->
			<div class="st-content"><!-- this is the wrapper for the content -->
				<div class="st-content-inner"><!-- extra div for emulating position:fixed of the menu -->
					<!-- Top Navigation -->
					<header>	
						<%= render "header" %>
					</header><!-- /main -->
				</div>
				<!-- /st-content-inner -->
				<%= render "before_returns" %>

				<footer>
					<%= render "footer" %>
				</footer> 
			</div><!-- /st-content -->
		</div><!-- /st-pusher -->
		<!-- /st-contain -->


		<script src="/assets/classie.js"></script>
		<script src="/assets/sidebarEffects.js"></script>
</div>
</div>

app/views/investors/index.html.erb
<h1>Investors#index</h1>
<p>Find me in app/views/investors/index.html.erb</p>

app/views/networks/_header.html.erb
<div class="header1 container">
	<div class="row">
		<div class="col-sm-1" style = "padding-left:0px; padding-right:0px;" >
			<div id="st-trigger-effects" class=" container column">
				<button data-effect="st-effect-2" class = "Btn">
					<em></em>
				</button>
			</div>
		</div>
		<div class="col-sm-2" style = "padding-left:6em; padding-right:0px;">
			<div class = "prodigy_logo">
			<img id="Prodigy_Finance" src="../assets/prodigy_finance_logo.png">
			</div>
		</div>
		<div class = "col-sm-9 linkto">
			<div class = "log_out">
		<%= link_to "Logout", destroy_investor_session_path, method: :delete%>
			</div>
			<div class = "log_out">
		<%= link_to "Documents", destroy_investor_session_path, method: :delete%>
			</div>
			<div class = "log_out">
		<%= link_to "Home", root_path %>
			</div>
		</div>
	</div>
</div>

app/views/networks/dashboard.html.erb
<%= render "navbar" %>

app/views/networks/show.html.erb
<div id = "dashboard">
<div id="st-container" class="st-container">
		<!-- 	
			example menus 
			these menus will be on top of the push wrapper
		-->
		

		<nav class="st-menu st-effect-2" id="menu-2">
			<h2> Investor Avatar</h2>
			<ul>
				<li><a class="dashboard" href= "/" >Dashboard</a></li>
				<li> <%= link_to "New Investment", new_investment_path %></li>
				<li><a class="current_investment" href="#">Current Investments</a></li>
				<li><a class="pastinvestment" href="#">Past Investments</a></li>
				<li><a class="social_impact" href="#">Social Impact</a></li>
				<li><%= link_to "Network", networks_show_path %></li>
				<li><a class="document" href="#">Documents</a></li>
				<li><a class="account" href="#">Account</a></li>
				<li><a class="faq" href="#">FAQ</a></li>
				<li><%= link_to "Logout", destroy_investor_session_path, method: :delete%></li>
			</ul>
		</nav>
		<!-- content push wrapper -->
		<div class="st-pusher">

			<!-- 	
				example menus 
				these menus will be under the push wrapper
			-->
			<div class="st-content"><!-- this is the wrapper for the content -->
				<div class="st-content-inner"><!-- extra div for emulating position:fixed of the menu -->
					<!-- Top Navigation -->
					<header>	
						<%= render "header" %>
					</header><!-- /main -->
				</div>
				<!-- /st-content-inner -->
				<%= render "show" %>

				<footer>
					<%= render "footer" %>
				</footer> 
			</div><!-- /st-content -->
		</div><!-- /st-pusher -->
		<!-- /st-contain -->


		<script src="/assets/classie.js"></script>
		<script src="/assets/sidebarEffects.js"></script>
</div>
</div>

app/views/student_impacts/index.html.erb
<%= render "content" %>